apiVersion: v1
name: compute
version: 1.0.0
appVersion: 2.2.0
description: A WPS based compute framework
keywords:
- ESGF
- CWT
- WPS
- compute
home: https://github.com/ESGF/esgf-compute-wps/README.md
sources:
- https://github.com/ESGF/esgf-compute-wps
maintainers:
- name: jboutte
  email: boutte3@llnl.gov
engine: gotpl
