traefik:
  dashboard:
    ingress:
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/hsts-max-age: "31536000"
        ingress.kubernetes.io/hsts-include-subdomains: "true"
        ingress.kubernetes.io/force-hsts: "true"

persistence:
  dataClaimName: data-pvc

  volumes:
    data:
      storageClassName: slow
      capacity: 100Gi
      path: /p/cscratch/nimbus/wps/data

    postgresql:
      storageClassName: slow
      capacity: 10Gi
      path: /opt/nimbus/wps/postgresql

    redis:
      storageClassName: slow
      capacity: 10Gi
      path: /opt/nimbus/wps/redis

wps:
  nodeSelector:
    tier: backend

  oauth:
    client:
    secret:

  apiUsername:
  apiPassword:

  externalHost:

  email:
    host:

  adminEmail:

celery:
  nodeSelector:
    tier: backend

  prometheusUrl:

provisioner:
  nodeSelector:
    tier: backend

kubeMonitor:
  nodeSelector:
    tier: backend

  namespace: production

nginx:
  nodeSelector:
    tier: backend

  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"

thredds:
  nodeSelector:
    tier: backend

  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"

postgresql:
  postgresqlPassword:

  master:
    nodeSelector:
      tier: backend
      storage/wps: local

redis:
  master:
    nodeSelector:
      tier: backend
      storage/wps: local

prometheus:
  enabled: false
