alertmanager:
  enabled: true
  prefixURL: /prometheus-alert
  baseURL: /prometheus-alert

  nodeSelector:
    tier: backend
    storage/prometheus: local

  ingress:
    enabled: true
    hosts:
    - /prometheus-alert

    annotations:
      ingress.kubernetes.io/auth-type: basic
      ingress.kubernetes.io/auth-secret: prometheus-secret
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"

    extraLabels:
      traffic-type: external

  persistentVolume:
    enabled: true
    existingClaim: prometheus-alert-pvc
    subPath: prometheus

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

configmapReload:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

initChownData:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

kubeStateMetrics:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

nodeExporter:
  image:
    tag: v0.18.0

  resources: 
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 30Mi

server:
  prefixURL: /prometheus
  baseURL: /prometheus

  nodeSelector:
    tier: backend
    storage/prometheus: local

  ingress:
    enabled: true
    hosts:
    - /prometheus

    annotations:
      ingress.kubernetes.io/auth-type: basic
      ingress.kubernetes.io/auth-secret: prometheus-secret
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/hsts-max-age: "31536000"
      ingress.kubernetes.io/hsts-include-subdomains: "true"
      ingress.kubernetes.io/force-hsts: "true"

    extraLabels:
      traffic-type: external

  persistentVolume:
    enabled: true
    existingClaim: prometheus-pvc
    subPath: prometheus

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi

pushgateway:
  enabled: false
