apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-thredds
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.thredds.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: thredds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: thredds
    spec:
      {{- if .Values.thredds.nodeSelector }}
      nodeSelector: 
        {{ .Values.thredds.nodeSelector | toYaml | trimSuffix "\n" }}
      {{- end }}
      {{- if $.Values.thredds.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.thredds.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ template "esgf-compute-wps.name" . }}-thredds
        image: {{ .Values.thredds.image }}:{{ .Values.thredds.imageTag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_HEAP_INIT
          value: {{ .Values.thredds.heapInit }}
        - name: JAVA_HEAP_MAX
          value: {{ .Values.thredds.heapMax }}
        livenessProbe:
          httpGet:
            path: /threddsCWT
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /threddsCWT
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 20
        resources: {{ $.Values.thredds.resources | toYaml | trimSuffix "\n" | nindent 10 }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data-volume
          mountPath: /data/public
          subPath: public
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.dataClaimName | default "data-pvc" }}
