apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-wps
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.wps.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: wps
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "esgf-compute-wps.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: wps
    {{- if .Values.wps.annotations }}
      annotations:
      {{- .Values.wps.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
    {{- end }}
    spec:
      {{- if .Values.wps.nodeSelector }}
      nodeSelector: 
        {{ .Values.wps.nodeSelector | toYaml | trimSuffix "\n" }}
      {{- end }}
      {{- if $.Values.wps.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.wps.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ template "esgf-compute-wps.name" . }}-wps
        image: {{ .Values.wps.image }}:{{ .Values.wps.imageTag }}
        imagePullPolicy: {{ .Values.wps.imagePullPolicy }}
        {{- if .Values.wps.development }}
        command:
          - tini
          - --
          - sleep
          - infinity
        {{- end }}
        {{- if not $.Values.development }}
        livenessProbe:
          httpGet:
            path: /api/ping/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/ping/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        {{- end }}
        resources: {{ $.Values.wps.resources | toYaml | trimSuffix "\n" | nindent 10 }}
        env:
        {{- if $.Values.wps.development }}
        - name: DEV
          value: "1"
        - name: WPS_DEBUG
          value: "1"
        {{- end }}
        - name: CELERY_BROKER_URL
          value: redis://{{ template "redis.fullname" . }}-master/0
        - name: CELERY_RESULT_BACKEND
          value: redis://{{ template "redis.fullname" . }}-master/0
        - name: POSTGRES_HOST
          value: {{ template "postgresql.fullname" . }}
        - name: PROVISIONER_FRONTEND
          value: {{ template "esgf-compute-wps.fullname" . }}-provisioner.{{ $.Release.Namespace }}.svc:{{ $.Values.provisioner.frontendPort }}
        envFrom:
        - secretRef:
            name: {{ template "esgf-compute-wps.fullname" . }}-wps
        ports:
        {{- range .Values.wps.ports }}
        - containerPort: {{ .port }}
          protocol: TCP
          name: {{ .name }}
        {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - mountPath: /data/public
          name: data-volume
          subPath: public
        {{- if .Values.wps.development }}
        - name: devel-volume
          mountPath: /devel
        {{- end }}
      volumes:
      {{- if .Values.wps.development }}
      - name: devel-volume
        hostPath: 
          path: /opt/cwt/devel
          type: DirectoryOrCreate
      {{- end }}
      - name: config-volume
        configMap:
          name: {{ template "esgf-compute-wps.fullname" . }}-wps
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.dataClaimName | default "data-pvc" }}
