apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "esgf-compute-wps.fullname" . }}-wps
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: {{ template "esgf-compute-wps.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
data:
  django.properties: |
    [default]
    {{- if .Values.wps.allowedCIDR }}
    allowed.cidr={{ .Values.wps.allowedCIDR }}
    {{- end }}
    host={{ required "Set wps.externalHost" .Values.wps.externalHost }}
    internal.lb={{ template "traefik.fullname" . }}.{{ .Release.Namespace }}.svc

    [email]
    host={{ required "Set wps.email.host" .Values.wps.email.host }}
    port={{ .Values.wps.email.port }}
    user={{ .Values.wps.email.user }}
    password={{ .Values.wps.email.password }}

    [wps]
    title={{ required "Set wps.title" .Values.wps.title }}
    abstract={{ required "Set wps.abstract" .Values.wps.abstract }}
    keywords={{ required "Set wps.keywords (list)" .Values.wps.keywords | join "," }}
    provider.name={{ required "Set wps.provider.name" .Values.wps.provider.name }}
    provider.site={{ required "Set wps.provider.site" .Values.wps.provider.site }}
    contact.name={{ .Values.wps.contact.name | default "Unknown" }}
    contact.position={{ .Values.wps.contact.position | default "Unknown" }}
    contact.phone={{ .Values.wps.contact.phone | default "Unknown" }}
    address.delivery={{ .Values.wps.address.delivery | default "Unknwon" }}
    address.city={{ .Values.wps.address.city | default "Unknwon" }}
    address.area={{ .Values.wps.address.area | default "Unknwon" }}
    address.postal={{ .Values.wps.address.postal | default "Unknwon" }}
    address.country={{ .Values.wps.address.country | default "Unknwon" }}
    address.email={{ .Values.wps.address.email | default "Unknwon" }}

    [output]
    fileserver.url=https://{{ .Values.wps.externalHost }}/threddsCWT/fileServer/public/{filename}
    dodsc.url=https://{{ .Values.wps.externalHost }}/threddsCWT/dodsC/public/{filename}
    local.path=/data/public

    [server]
    external.url=https://{{ .Values.wps.externalHost }}
    admin.email={{ required "Set wps.adminEmail" .Values.wps.adminEmail }}

    [external]
    jobs.url=https://{{ .Values.wps.externalHost }}/user/jobs
    login.url=https://{{ .Values.wps.externalHost }}/auth/login
    profile.url=https://{{ .Values.wps.externalHost }}/user/profile
    openid.callback.success.url=https://{{ .Values.wps.externalHost }}/auth/login/callback
